server:
  port: 8081
spring:
  application:
    name: ms-bank-product-rule-service
  config:
    import: optional:configserver:http://ms-bank-config-server:8888
  data: 
    mongodb:
     host: mongo
     port: 27017
     database: Bank 
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-bank-discovery-service:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    
client.msbankproduct.url: http://ms-bank-apigateway-service:9090/product