server:
  port: 8761
spring:
  application:
    name: ms-bank-discovery-service
  config:
    import: optional:configserver:http://ms-bank-config-server:8888
eureka:
  client:
    #telling the server not to register himself in the service registry
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0    #wait time for subsequent sync
logging:
  level:
    '[com.netflix.eureka]': 'OFF'
    '[com.netflix.discovery]': 'OFF'