server:
  port: 9090
spring:
  application:
    name: ms-bank-apigateway-service
  config:
    import: optional:configserver:http://ms-bank-config-server:8888
  cloud:
    gateway:
      default-filters:
      - name: SCGWGlobalFilter
      routes:
        - id: ms-bank-product-service
          uri: http://ms-bank-product-service:8080/
          predicates:
            - Path=/product/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter
        - id: ms-bank-product-rule-service
          uri: http://ms-bank-product-rule-service:8081/
          predicates:
            - Path=/productRule/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter
        - id: ms-bank-account-service
          uri: http://ms-bank-account-service:8082/
          predicates:
            - Path=/account/**
          filters:
          - name: SCGWPreFilter
          - name: SCGWPostFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-bank-discovery-service:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true